"""
AUCTUS Capital Partners AG — Report Builder

Assembles final markdown investment reports from script output artifacts.
Reads JSON/CSV results and formats them into structured markdown.

Usage:
    python scripts/report_builder.py \
        --workflow dcf \
        --manifest outputs/dcf_models/company_20260629_dcf_results.json \
        --output-dir outputs/dcf_models/ \
        --company-name "Muster GmbH"

Exit codes:
    0  success
    1  manifest not found
    3  output write error
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stderr)],
)
logger = logging.getLogger(__name__)


def _fmt_eur(value: float) -> str:
    return f"€{value:.2f}m"


def build_dcf_report(manifest: dict, output_dir: Path, company_name: str) -> Path:
    ts = manifest.get("run_timestamp", datetime.utcnow().strftime("%Y%m%d_%H%M%S"))
    slug = company_name.lower().replace(" ", "_").replace("/", "_")

    ev = manifest.get("enterprise_value_eur_m", 0.0)
    wacc = manifest.get("wacc_used", 0.0)
    tgr = manifest.get("terminal_growth_rate_used", 0.0)
    tv_pct = manifest.get("terminal_value_pct_of_ev", 0.0)
    pv_fcf = manifest.get("pv_forecast_cashflows_eur_m", 0.0)
    tv_pv = manifest.get("terminal_value_pv_eur_m", 0.0)

    sensitivity_path = output_dir / f"{slug}_{ts}_sensitivity.csv"
    sensitivity_table = ""
    if sensitivity_path.exists():
        sens_df = pd.read_csv(sensitivity_path, index_col=0)
        sens_df.index = [f"{float(i)*100:.2f}%" for i in sens_df.index]
        sens_df.columns = [f"{float(c)*100:.2f}%" for c in sens_df.columns]
        sensitivity_table = sens_df.to_markdown()

    cashflows_path = manifest.get("cashflows_path", "")
    cf_table = ""
    if cashflows_path and Path(cashflows_path).exists():
        cf_df = pd.read_csv(cashflows_path)
        display_cols = [c for c in ["year", "revenue", "ebitda", "ufcf", "pv_ufcf"] if c in cf_df.columns]
        cf_table = cf_df[display_cols].round(2).to_markdown(index=False)

    lines = [
        f"# DCF Valuation Report — {company_name}",
        f"**Run Date:** {ts[:8]}  |  **Model:** AUCTUS DCF Engine v1.0",
        f"**WACC:** {wacc*100:.2f}%  |  **Terminal Growth Rate:** {tgr*100:.2f}%",
        "",
        "---",
        "",
        "## Enterprise Value Summary",
        "",
        f"| Component | Value |",
        f"|-----------|-------|",
        f"| PV of Forecast FCFs | {_fmt_eur(pv_fcf)} |",
        f"| PV of Terminal Value | {_fmt_eur(tv_pv)} |",
        f"| **Enterprise Value** | **{_fmt_eur(ev)}** |",
        f"| Terminal Value as % of EV | {tv_pct*100:.1f}% |",
        "",
        "---",
        "",
        "## 5-Year Cash Flow Projections",
        "",
        cf_table or "*Cash flow data not available.*",
        "",
        "---",
        "",
        "## Sensitivity Analysis",
        "*Rows: WACC | Columns: Terminal Growth Rate | Values: Enterprise Value (€m)*",
        "",
        sensitivity_table or "*Sensitivity data not available.*",
        "",
        "---",
        "",
        "## WACC Rationale",
        f"WACC of **{wacc*100:.2f}%** applied. Derived from sector parameters in "
        "`skills/dcf-valuation/refs/wacc-assumptions.yaml` or user-specified value.",
        "",
        f"*Source: `{manifest.get('cashflows_path', 'N/A')}` — `enterprise_value_eur_m`*",
        "",
        "---",
        "",
        "*Report generated by AUCTUS Investment Intelligence Agent. "
        "All financial calculations performed by deterministic Python scripts. "
        "This report is for internal AUCTUS use only.*",
    ]

    report_path = output_dir / f"{slug}_{ts}_report.md"
    report_path.write_text("\n".join(lines))
    logger.info("DCF report written: %s", report_path)
    return report_path


def main() -> int:
    parser = argparse.ArgumentParser(description="AUCTUS Report Builder")
    parser.add_argument("--workflow", choices=["dcf", "comps", "competitor"], required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True, dest="output_dir")
    parser.add_argument("--company-name", type=str, default="company", dest="company_name")
    args = parser.parse_args()

    if not args.manifest.exists():
        logger.error("Manifest not found: %s", args.manifest)
        return 1

    try:
        with open(args.manifest) as f:
            manifest = json.load(f)
    except json.JSONDecodeError as exc:
        logger.error("Cannot parse manifest JSON: %s", exc)
        return 1

    try:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        if args.workflow == "dcf":
            out = build_dcf_report(manifest, args.output_dir, args.company_name)
        else:
            logger.warning("Report builder for workflow '%s' not yet implemented.", args.workflow)
            return 0
        print(json.dumps({"status": "success", "report_path": str(out)}))
        return 0
    except OSError as exc:
        logger.error("Output write error: %s", exc)
        return 3


if __name__ == "__main__":
    sys.exit(main())
